version: '3.8'

services:
  app:
    container_name: agilaflask
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/mmanez/projects/agilaflask:cached
    command: sleep infinity
    network_mode: service:db
  db:
    container_name: agilaflask_db
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3311:3306
volumes:
  mysql-data:
